modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = "Recreation of a classical card game in Minecraft"
    logoFile = "minopp.png"
    authors = "Zbx1425, MalayP"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mc}"
    ordering = "NONE"
    side = "BOTH"
